### PR TITLE
Add Lattice MachXO3LF Starter Kit

### PR DESCRIPTION
**Pull request by trabucayre**
Hello,
This is the board definition for the Lattice MachX03LF Starter Kit.
Successfully tested  with the blinky example.

Regards,
Gwenhael Goavec-Merou

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks for the PR; looks reasonable to me. There's one minor issue though; are you sure that using the MachXO2 platform is appropriate?

**Comment by trabucayre** [comment]
I'm agree, it's seems a bit strange but all my tests with this platform and my machXO3 based board works well... 
In fact, before sending this PR, I have hesitated due to this "detail".
Of course maybe I'm wrong but...

**Comment by whitequark** [comment]
Okay, I checked and all of the primitives match between MachXO2 and MachXO3L, so we should rename the platform to something like `vendor.lattice_machxo_2_3l`.

**Comment by trabucayre** [comment]
True. It's maybe less error prone.
Would you like I do it? with this name?

**Comment by whitequark** [comment]
> Would you like I do it? with this name?

Yes. Please look at how it's done for Xilinx, and do the same for MachXO.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
