### PR TITLE
Add GPDI pins to ulx3s.py

### PR DESCRIPTION
**Pull request by GuzTech**
This adds the GPDI pins to the ULX3S platform. The constraints were taken from https://github.com/emard/ulx3s-misc/blob/master/constraints/ulx3s_v20.lpf

### CODE REVIEW

**Comment by whitequark** [comment]
What is "GPDI"?

**Comment by GuzTech** [comment]
It is the HDMI port (but it's called the General Purpose Differential Interface for licensing reasons).

**Comment by awygle** [comment]
It would be nice to be consistent with other HDMI resources, even if the name is different. That would mean collecting the signals into a single `Resource` with `Subsignal`s. I think the Arty Z7 offers the most complete example:

```python
        Resource("hdmi_rx", 0,                                  # J10
            Subsignal("cec", Pins("H17", dir="io")),
            Subsignal("clk", DiffPairs("N18", "P19", dir="i"),
                Attrs(IOSTANDARD="TMDS_33")),
            Subsignal("d",   DiffPairs("V20 T20 N20", "W20 U20 P20", dir="i"),
                Attrs(IOSTANDARD="TMDS_33")),
            Subsignal("hpd", Pins("T19", dir="o")),
            Subsignal("scl", Pins("U14", dir="io")),
            Subsignal("sda", Pins("U15", dir="io")),
            Attrs(IOSTANDARD="LVCMOS33")),
```
Can you please make this resource follow this style?

**Comment by GuzTech** [comment]
Since the ~~GPDI~~ HDMI port is directly connected to the FPGA and can therefore be used as a source as well as a sink, do you think it would be better to define a single resource as bidirectional, or as two separate resources (one for rx, one for tx)?

**Comment by awygle** [comment]
The convention (derived from the `atlys.py` and `supercon19badge.py` files) appears to be a single resource. Compare/contrast:

```python
        Resource("hdmi", 2, # J3, input only due to on board buffer, HDMI A connector
            Subsignal("scl",     Pins("M16"), Attrs(IOSTANDARD="I2C")),
            Subsignal("sda",     Pins("M18"), Attrs(IOSTANDARD="I2C")),
            Subsignal("clk",     DiffPairs("H17", "H18", dir="i")),
            Subsignal("d",       DiffPairs("K17 L17 J16", "K18 L18 J18", dir="i")),
            Attrs(IOSTANDARD="TMDS_33"),
        ),
        Resource("hdmi", 3, # JA, input/output as it is unbuffered, HDMI D connector
            Subsignal("scl",     Pins("C13"), Attrs(IOSTANDARD="I2C")),
            Subsignal("sda",     Pins("A13"), Attrs(IOSTANDARD="I2C")),
            Subsignal("clk",     DiffPairs("T9", "V9")),
            Subsignal("d",       DiffPairs("R3 T4 N5", "T3 V4 P6")),
            Attrs(IOSTANDARD="TMDS_33"),
        ),
```

**Comment by GuzTech** [comment]
All right, one resource it is. In your first example, the directions are explicit, but in the second one they are implicit for "hmdi, 3". Which one is preferred?

**Comment by awygle** [comment]
I'd recommend being explicit, I think it causes less confusion down the line.

**Comment by awygle** [comment]
Thanks a lot! This looks good to me now, when whitequark gets back from vacation we'll see what she says :)

**Review by whitequark — APPROVED** [review]

**Comment by whitequark** [comment]
Thank you!

**Pull request merged**
