### PR TITLE
genesys2: employ ULPI resource.

### PR DESCRIPTION
**Pull request by peteut**
Emply `ULPIResource` introduced by dd0bb11f096bd823fb7f1e73384d7541213434ce. 

Note: *rst* is actually active low (Texas Instruments TUSB1210).

### CODE REVIEW

**Comment by whitequark** [comment]
> Note: _rst_ is actually active low (Texas Instruments TUSB1210).

Then `ULPIResource` needs to be changed so that this can be reflected properly.

**Comment by peteut** [comment]
Added `rst_invert=True`. Missed that `ULPIResource` already handles inverted `rst`.

**Comment by peteut** [comment]
Now obsolete, as resolved by 0e95118062b86e8e57f064957088ddb84cfb31ed.

**Comment by whitequark** [comment]
Ah sorry, I seem to have missed this PR.

**Pull request closed without merging**
